name: Actualizacion Automatica OVP

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osgeo/gdal:ubuntu-small-latest

    permissions:
      contents: write

    steps:
      - name: Instalar Git en el contenedor
        run: apt-get update && apt-get install -y git

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ejecutar script de actualización
        run: python main.py

      - name: Guardar y publicar archivos actualizados (.ics y .kml)
        run: |
          git add .
          git commit -m "Actualización automática de ICS y KML" || exit 0
          git push
