name: Actualizacion Automatica OVP

on:
  schedule:
    - cron: '*/5 * * * *' # Ejecución cada 5 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osgeo/gdal:ubuntu-small-latest

    permissions:
      contents: write

    steps:
          - name: Instalar dependencias del sistema (Git y Pip)
            run: |
              apt-get update
              apt-get install -y git python3-pip
    
          - name: Descargar repositorio
            uses: actions/checkout@v4
    
          - name: Configurar Git
            run: |
              git config --global --add safe.directory "$GITHUB_WORKSPACE"
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
          - name: Instalar dependencias de Python
            run: python3 -m pip install pandas openpyxl requests
    
          - name: Ejecutar script de actualización
            run: python3 main.py
    
          - name: Guardar y publicar archivos actualizados (.ics, .kml y .gpkg)
            run: |
              git add .
              git commit -m "Actualización automática desde Excel Online" || exit 0
              git push
