name: Actualizacion Automatica OVP

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite que el bot guarde cambios con git push

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar GDAL / OGR en el servidor
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev gdal-bin
          pip install GDAL==$(gdal-config --version)

      - name: Ejecutar script de actualización
        run: python main.py

      - name: Guardar y publicar archivos actualizados (.ics y .kml)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Actualización automática de ICS y KML" || exit 0
          git push
